### ISSUE TITLE
20 parameter limit

### ISSUE THREAD

**Issue by dahuanghuang** [thoughtbot/Curry#52]
Hi ,

I'm using version Curry (v4.0.2) with CocoaPods。

Xcode version 11.5

a issues that curry parameters are limited to 20. What should I do if there are more than 20 parameters

**Comment by gfontenot** [comment]
We're limited to only shipping 20 arguments because beyond that the compiler starts getting exponentially slower with each new argument added. That being said, I think you might be able to define `curry` for as many arguments as you'd like in your own codebase and not pay the entire cost. If you copy the 20 argument implementation out of this library it should be straightforward (if not cumbersome) to modify for however many arguments you need.

**Comment by mokagio** [comment]
@dahuanghuang you can also checkout this repo and run `./bin/generate n` to code-generate the implementation, e.g: `./bin/generate 30` will add implementations for 21 to 30 parameters.

**Comment by dahuanghuang** [comment]
OK, thanks
